coverage: false
# corpusDir: echidna-corpus
seqLen: 3
testLimit: 50000
shrinkLimit: 1000

cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  [
    '--solc-remaps',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/ @openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
  ]
